### ISSUE TITLE
New xdsl version was not properly tested by CI?

### ISSUE THREAD

**Issue by JosseVanDelm** [KULeuven-MICAS/snax-mlir#52]
It looks like using the docker cache with the newer version of xdsl is breaking some things:
```
/repo/runtime//../compiler/snax-opt -p set-memory-space,insert-sync-barrier,dispatch-regions,dispatch-elementwise-mult,linalg-to-library-call,snax-copy-to-dma,snax-to-func,clear-memory-space -o linalg.snax-opt.mlir linalg.preproc.mlir
/opt/python3.11/lib/python3.11/site-packages/xdsl/utils/deprecation.py:18: UserWarning: Call to deprecated method MemRefType.from_element_type_and_shape: use the constructor (`ClassName(...)`) instead.
  warnings.warn(
Traceback (most recent call last):
  File "/repo/runtime//../compiler/snax-opt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/repo/compiler/tools/snax_opt_main.py", line 58, in main
    SNAXOptMain().run()
  File "/opt/python3.11/lib/python3.11/site-packages/xdsl/xdsl_opt_main.py", line 70, in run
    if self.apply_passes(module):
       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/xdsl/xdsl_opt_main.py", line 276, in apply_passes
    self.pipeline.apply(self.ctx, prog)
  File "/opt/python3.11/lib/python3.11/site-packages/xdsl/passes.py", line 177, in apply
    prev.apply(ctx, op)
  File "/repo/compiler/transforms/set_memory_space.py", line 229, in apply
    PatternRewriteWalker(RealizeMemorySpaceCasts()).rewrite_module(op)
  File "/opt/python3.11/lib/python3.11/site-packages/xdsl/pattern_rewriter.py", line 641, in rewrite_module
    self._rewrite_op(op)
  File "/opt/python3.11/lib/python3.11/site-packages/xdsl/pattern_rewriter.py", line 689, in _rewrite_op
    self._rewrite_op_regions(op)
  File "/opt/python3.11/lib/python3.11/site-packages/xdsl/pattern_rewriter.py", line 702, in _rewrite_op_regions
    iter_op = self._rewrite_op(iter_op)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/xdsl/pattern_rewriter.py", line 689, in _rewrite_op
    self._rewrite_op_regions(op)
  File "/opt/python3.11/lib/python3.11/site-packages/xdsl/pattern_rewriter.py", line 702, in _rewrite_op_regions
    iter_op = self._rewrite_op(iter_op)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/python3.11/lib/python3.11/site-packages/xdsl/pattern_rewriter.py", line 657, in _rewrite_op
    self.pattern.match_and_rewrite(op, rewriter)
  File "/opt/python3.11/lib/python3.11/site-packages/xdsl/pattern_rewriter.py", line 454, in impl
    func(self, op, rewriter)
  File "/repo/compiler/transforms/set_memory_space.py", line 158, in match_and_rewrite
    shapes = [x.value.data for x in op.results[0].type.shape.data]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/repo/compiler/transforms/set_memory_space.py", line 158, in <listcomp>
    shapes = [x.value.data for x in op.results[0].type.shape.data]
              ^^^^^^^
AttributeError: 'IntAttr' object has no attribute 'value'
../../runtime/Makefile.rules:95: recipe for target 'linalg.snax-opt.mlir' failed
```
Is this related to https://github.com/xdslproject/xdsl/pull/1825

**Comment by jorendumoulin** [comment]
Not really related to docker cache, but rather the tests running on the main docker build rather than the updated docker build from the PR, see #53
